### ISSUE TITLE
How to get flops for backbone‘s flops and params?

### ISSUE THREAD

**Issue by dzyjjpy** [open-mmlab/mmrazor#150]
Try to use tools/misc/get_flops to calcalate model's params and flops, However, I'm not sure whether use the tool right or not.

For example,  readme shows: 
https://github.com/open-mmlab/mmrazor/blob/master/configs/nas/detnas/README.md
params: 3.35M flops: 0.35G

I use the following command to calculate:
`python tools/misc/get_flops.py configs/nas/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco.py --shape 1333 800`
params: 25.69M flops: 262.05G

**Comment by pppppM** [comment]
Your result is correct, the result in the README is the flops of the backbone part, excluding the neck and head parts.

**Comment by dzyjjpy** [comment]
> 

Got it, thanks for your reply.  
As you said, the model's neck & head's params/flops is much more than backbone.  The model is unbalanced.
If I want to slim neck and head parts, is there any automatic tools to finish these work? Or I have to finish mannually? @pppppM @wutongshenqiu

**Comment by pppppM** [comment]
BTW, have you set `mutable_cfg`? 
If not, these should be the results of the whole supernet.

In MMRazor, one `mutable_cfg` represents one subnet, and the usage of `mutable_cfg` can be found here.
https://github.com/open-mmlab/mmrazor/tree/master/configs/nas/detnas#step-4-subnet-retraining-on-imagenet

**Comment by dzyjjpy** [comment]
> BTW, have you set `mutable_cfg`? If not, these should be the results of the whole supernet.
> 
> In MMRazor, one `mutable_cfg` represents one subnet, and the usage of `mutable_cfg` can be found here. https://github.com/open-mmlab/mmrazor/tree/master/configs/nas/detnas#step-4-subnet-retraining-on-imagenet

set:
`--cfg-options algorithm.mutable_cfg=configs/nas/detnas/DETNAS_FRCNN_SHUFFLENETV2_340M_COCO_MMRAZOR.yaml`

I test without set mutable_cfg. The result has no difference.
![image](https://user-images.githubusercontent.com/18523654/165286007-43a96c30-e1a0-47d9-8017-b7aaf9b02b7b.png)

**Comment by wutongshenqiu** [comment]
Hi, dzyjjpy. Did you modify the `retraining` attribute to `False` in config? Here is my `configs/nas/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco.py`
```python
_base_ = ['./detnas_supernet_frcnn_shufflenetv2_fpn_1x_coco.py']
algorithm = dict(retraining=True)
```
If `retraining` is set to `True`, when calculating flops, mutable_cfg must be provided, otherwise the program will raise `NotImplementedError`

By the way, we get the flops according to [DetNAS official repo](https://github.com/megvii-model/DetNAS/blob/master/distributed_arch_search/search.py#L93), and they only calculate backbone flops with input shape `[3, 224, 224]`, so you might try first modify [this line in `tools/misc/get_flops.py`](https://github.com/open-mmlab/mmrazor/blob/master/tools/misc/get_flops.py#L74) to

```python

flops, params = get_model_complexity_info(algorithm.architecture.model.backbone, input_shape)

```


and use the following command.

```bash
python tools/misc/get_flops.py configs/nas/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco.py --cfg-options algorithm.mutable_cfg=configs/nas/detnas/DETNAS_FRCNN_SHUFFLENETV2_340M_COCO_MMRAZOR.yaml --shape 224 224
```

the result is as follows 
![image](https://user-images.githubusercontent.com/44188071/165316063-2a03b218-329e-4ce7-9563-25163b95f35c.png)

it's lower than [we report](https://github.com/open-mmlab/mmrazor/tree/master/configs/nas/detnas#results-and-models) since we might calculate the flops of whole classfication model(backbone + neck + classification head)

**Comment by dzyjjpy** [comment]
![image](https://user-images.githubusercontent.com/18523654/165287939-bfb42714-e790-491b-8834-ecd83e3cbd44.png)


> If `retraining` is set to `True`, when calculating flops, mutable_cfg must be provided, otherwise the program will raise `NotImplementedError`
I set retraining=True. There is no difference as I set mutable_cfg parameter inside the config file.

I change the line in get_flops.py , got the same result as you post 

thanks :)
