### ISSUE TITLE
is there any plan to support once-for-all NAS?

### ISSUE THREAD

**Issue by wmkai** [open-mmlab/mmrazor#172]
Hi, is there any plan to support once-for-all NAS?

**Comment by pppppM** [comment]
Yes, we are developing OFA, but it will take a while

**Comment by wmkai** [comment]
OK, thanks for your reply!

**Comment by twmht** [comment]
@pppppM 

I am also investigative OFA.

The main contributions of OFA is that they use four dimenstions and progessive shrink, and they said prograssive shrink can prevent from interfering between subnets. what is your opinion? From my opinion even use prograssive shink, we still can not escape this problem, since the weight is shared.

**Comment by pppppM** [comment]
I agree with your opinion.
I think OFA doesn't solve the problem, and it just alleviates the problem.
I think slimmable training in bignas may be better for this problem, but it doesn't solve the problem either.

> @pppppM
> 
> I am also investigating OFA.
> 
> The main contributions of OFA are that they use four dimenstions and progessive shrink, and they said prograssive shrink can prevent from interfering between subnets. what is your opinion? From my opinion even use prograssive shink, we still can not escape this problem, since the weight is shared.

**Comment by pppppM** [comment]
The processing logic of bignas should be different from that of autoslim, and it should be that all blocks in each stage have the same out channels.

This is not particularly clear in the paper, but according to the searched model structure shown in the paper and the processing logic in FBNET-series， I guess it should be like this.
