### ISSUE TITLE
Question on bn_training_mode=True in the Search Phase of DetNas

### ISSUE THREAD

**Issue by TianpengBu** [open-mmlab/mmrazor#298]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet
Thanks for your great work. From the config file of detnas algorithm, you set bn_training_mode=True, as you want to update the BN statistics during evaluation of subnets. 

However, this behavior is different from the original implementation. Because of the existance of the momentum in BN, your implementation will update the BN statistics on the basis of the trained supernet during the search phase. 

But the paper states that re-init the BN statistics (running mean = 0 and running var = 1) during the searching of each subnet, and then calibrate these statistics before doing the evaluation of subnets.

As far as I am concerned, the way you did might cause two side effects: 
1. During searching, you update BN statistics of the chosen subnet based on the supernet history, and this is not optimal for the selected subnet, and is not as good as the reinit-and-recalibrate manner. 
2. Since parameter sharing, during searching, the historical changes of BN statistics of a specific choice block will affect the performance of other combinations if this block is chosen in another subnet in the furture.

I am wondering these above two opinions are correct or not. It would be nice that you can put your opinions on these two questions! 

Best regards

**Comment by humu789** [comment]
In my opinion, if take the searching as an independent task, the implementation in the paper is actually better. But the searching is related to the supernet training. When the supernet is trained adequately and each part of the supernet has an equivalent contribution to the result, the searched subnet is really best. So we want to unify the experiment settings of some similar algorithms rather than reproduce them fully. Thus we can find that improvement in the accuracy is mainly from the main contribution in papers or from some extra tricks.
If you are interested in verifying the difference by experiments, welcome to tell us and contribute to mmrazo with a PR.

**Comment by TianpengBu** [comment]
Well, thanks for the quick reply. I will first verify the consequences of BN statistics on my own task (perdestrain detection based on mmdetection implemented yolox).
